name: Suleiman Leadbitter | Designer, Developer, Illustrator
<<<<<<< HEAD
title: Suljam | Designed with Standards
email: sul@suljam.com
description: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odit, iste aliquam ea. Vel rem vitae dicta quidem at deserunt debitis quia illo autem, consequuntur architecto atque, molestiae. Illo veniam quisquam ad laborum.
baseurl: ""
url: http://suljam.com
personalurl: http://sulcalibur.com
twitter_username: sulcalibur
github_username: sulcalibur

# Build Settings
=======
>>>>>>> parent of 6ee0218... Getting ready to upload to Github Pages
markdown: redcarpet
exclude: ["node_modules", "gulpfile.js", "package.json"]
